### ISSUE TITLE
Work on Raspberry Pi 4?

### ISSUE THREAD

**Issue by philletourneau** [hslatman/tailscale-balena-rpi#1]
I haven't been able to get this working on the Pi4, is that something that needs to be done in the project?

**Comment by philletourneau** [comment]
I've worked something out... I'll fork the repo and put it up. Thanks for your work!

**Comment by hslatman** [comment]
@philletourneau: great! If your changes are backwards compatible with RPi3, you could choose to create a PR. I know that I had some issues supporting multiple different kinds of Pis and architectures when working on this thing though, so it may not be that easy with the Pi 4.

Since then Balena created "Blocks", which I figured was a nice fit for this Tailscale node. I have another repo up for that here: https://github.com/hslatman/tailscale-balena-block. A Balena team member has a PR open that's set to support the Pi 4 too, so maybe that works for you too.
